<?php
/**
 * Created by PhpStorm.
 * User: MyPc
 * Date: 2019/4/17 0017
 * Time: 21:14
 */
namespace app\admin\controller;

use think\Db;

class Admin extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        return $this->fetch();
    }

    //管理员列表
    public function lists()
    {
        $where['id'] = ['>', 0];
        $datemin = '';
        $datemax = '';
        $seach = isset($_GET['seach']) ? $_GET['seach'] : '';
        $page = 10;

        //搜索条件
        if($seach){
            $page = 0;
            $time = " 23:59:59";
            if($seach['m_conditions']){
                $m_conditions = str_replace(' ', '', $seach['m_conditions']);
                $where['name'] = ['like',"%$m_conditions%"];
            }
            if ($seach['datemin'] && $seach['datemax']) {
                $datemin = strtotime($seach['datemin']);
                $datemax = strtotime($seach['datemax'].$time);
                $where['addtime'] = [['>= time',$datemin],['<= time',$datemax],'and'];
            } elseif ($seach['datemin']) {
                $where['addtime'] = ['>= time',strtotime($seach['datemin'])];
            } elseif ($seach['datemax']) {
                $where['addtime'] = ['<= time',strtotime($seach['datemax'].$time)];
            }
        }
//        dump($seach);//die;
        $list = Db::name('admin')->where($where)->paginate($page);//dump($list);die;
        $count = count($list);
        $this->assign('seach',$seach);

        $this->assign('list',$list);
        $this->assign('count',$count);
        return $this->fetch();
    }

    //添加管理员
    public function add()
    {
        $data = input('post.');
        $act = 'add';
        $this->assign('act',$act);
        $this->assign('data',$data);
        return $this->fetch();
    }

    //管理员编辑
    public function edit()
    {
        $admin_id = input('get.id/d');
        $info = Db::name('admin')->where('id',$admin_id)->find();
//        dump($info);die;
        $act = 'edit';
        $this->assign('info',$info);
        $this->assign('act',$act);
        $this->assign('admin_id',$admin_id);
        return $this->fetch();
    }

    public function handle()
    {
        $data = input('post.');//dump($data);die;
        $return = ['status'=>0,'msg'=>'参数错误']; //初始化返回信息
        if($data['act'] == 'add'){
            $is_name = Db::name('admin')->where('name',$data['adminName'])->find();
            if(!empty($is_name)){
                return json(['status'=>0,'msg'=>'已经有此管理员了！']);
            }
            $data1 = [
                'name'    => $data['adminName'],
                'password'=> md5($data['password']),
                'is_super'=> $data['adminRole'],
                'addtime' => time()
            ];
            $res = Db::name('admin')->insert($data1);
            if($res) {
                return json(['status'=> 1, 'msg'=> '添加成功']);
            }else {
                return json(['status'=> 0, 'msg'=> '添加失败，数据库未响应']);
            }
        }
        if($data['act'] == 'edit'){
            $data1 = [
                'name'    => $data['adminName'],
                'password'=> pwd_encryption($data['password']),
                'is_super'=> $data['adminRole'],
                'addtime' => time()
            ];
            $res = Db::name('admin')->where('id',$data['admin_id'])->update($data1);
            if($res) {
                return json(['status'=> 1, 'msg'=> '添加成功']);
            }else {
                return json(['status'=> 0, 'msg'=> '添加失败，数据库未响应']);
            }
        }

        if ($data['act'] == 'status') {
            $status = intval($data['status']);
            $status = ($status == 1) ? $status : 0;
            $bool = Db::name('admin')->where('id',$data['id'])->update(['is_lock'=>$status]);

            if ($bool) {
                return json(['code' => 1]);
            } else {
                return json(['code' => 0]);
            }
        }

    }

    //删除管理员
    public function del()
    {
        $data = input('post.');
        if ($_POST){
            $id = json_decode($data['id'], true);
            $where['id'] = array('in', $id);
            $res = Db::table('zf_admin')->where($where)->delete();
            if($res){
                return json(['status'=>1,'msg'=>'删除成功']);
            }else {
                return json(['status'=>1,'msg'=>'删除失败']);
            }
        }
    }

    public function role()
    {
        return $this->fetch();
    }

    public function role_add()
    {
        return $this->fetch();
    }

    public function permission()
    {
        return $this->fetch();
    }

    public function permission_add()
    {
        return $this->fetch();
    }

}