<?php
/**
 * Created by PhpStorm.
 * User: MyPc
 * Date: 2019/4/17 0017
 * Time: 21:14
 */
namespace app\admin\controller;

class Admin extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        return $this->fetch();
    }

    public function lists()
    {
        return $this->fetch();
    }

    public function add()
    {
        return $this->fetch();
    }

    public function role()
    {
        return $this->fetch();
    }

    public function role_add()
    {
        return $this->fetch();
    }

    public function permission()
    {
        return $this->fetch();
    }

    public function permission_add()
    {
        return $this->fetch();
    }

}