<?php
/**
 * Created by PhpStorm.
 * User: MyPc
 * Date: 2019/4/23 0023
 * Time: 18:04
 */
namespace app\admin\controller;

use think\Db;

class Article extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function lists()
    {
        $list = Db::name('article')->paginate(10);
        $count = count($list);

        $this->assign('list',$list);
        $this->assign('count',$count);
        return $this->fetch();
    }

    public function add()
    {
        return $this->fetch();
    }

    public function edit()
    {
        return $this->fetch();
    }
}