<?php
/**
 * Created by PhpStorm.
 * User: MyPc
 * Date: 2019/4/17 0017
 * Time: 21:35
 */
namespace app\admin\controller;

class System extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function setting()
    {
        return $this->fetch();
    }

    public function category()
    {
        return $this->fetch();
    }

    public function category_add()
    {
        return $this->fetch();
    }

    public function data()
    {
        return $this->fetch();
    }

    public function shielding()
    {
        return $this->fetch();
    }

    public function log()
    {
        return $this->fetch();
    }

}