<?php
namespace app\index\controller;

use think\Db;
class Index extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        check_user();
    }
    //首页
    public function index()
    {
//        echo 123;
        //调用公告
        $article=Db::name('article')->where('type','0')->order('add_time desc')->find();
        if (isset($article['content'])&&$article['content']!=''){
            if(strlen($article['content'])>66){
                $flag="...";
            }else{
                $flag='';
            }
            $article['content']=substr($article['content'],0,66).$flag;
        }else{
            $article['content']='暂无公告';
            $article['id']=0;
        }
        //看看用户到期了没有
        $user_id=session('user.user_id');
        $is_end=Db::name('users')->where(['id'=>$user_id])->where('end_time','<',time())->count();
        $this->assign('is_end',$is_end);
        $this->assign('notice',$article);
        return $this->fetch();
    }
    //列表页
    public function lottery_list(){
        $type=input('type');
        $num=input('num',1);
        $is_ajax=input('is_ajax',0);
        $user_id=session('user.user_id');
//        $user_id=1;//在登录做好之前暂用
//        echo $type;
        if(in_array($type,array(1,2,3,4))){
            $page=10;
            $max=($num-1)*$page+1;
            $list=Db::name('interface_recorder')->where(['type'=>$type])->order('lottery_date desc')->limit($max,$page)->select();
//print_r($list);die;
            //把所有选择过的颜色存起来
            $all_color=array();
            foreach ($list as $key=>$value){
                $list[$key]['lottery_number_text']=$value['lottery_number'];
                $list[$key]['lottery_number']=explode(',',$value['lottery_number']);
//                foreach($list[$key]['lottery_number'] as $k=>$v){
//                    $list[$key]['lottery_color'][$k."_".$v]=$this->get_lottery_color($user_id,$type,$v);
//                }
                $list[$key]['lottery_time']=date('Y',$value['lottery_time'])."年".date('m',$value['lottery_time'])."月".date('d',$value['lottery_time']).'日'.' '.date('H:i:s',$value['lottery_time']);
            }
            if($type==4){
                for($i=1;$i<10;$i++){
                    $all_color[$i]=$this->get_lottery_color($user_id,$type,$i,1);
                }
                $all_color[10]=$this->get_lottery_color($user_id,$type,0,1);
            }else{
                for($i=1;$i<11;$i++){
                    $all_color[$i]=$this->get_lottery_color($user_id,$type,$i,1);
                }
            }
//            var_dump($list);die;
//            $pages = $list->render();
//            ksort($all_color);
//            var_dump($all_color);die;
            $this->assign('list', $list);
            $this->assign('page', $num);
            $this->assign('all_color',$all_color);
//            var_dump($all_color);die;
            //展示最新一条
            switch ($type){
                case 1:
                    $typed='幸运飞艇';
                    break;
                case 2:
                    $typed='快乐飞艇';
                    break;
                case 3:
                    $typed='快乐赛车';
                    break;
                case 4:
                    $typed='快乐时时彩';
                    break;
            }
            if($is_ajax){
                foreach ($list as $ke=>$val){
                    foreach($val['lottery_number'] as $l=>$p){
                        $list[$ke]['lottery_new_color'][$l.'-'.$p]=$this->get_lottery_color($user_id,$type,$p);
                    }
                }
                $this->ajaxReturn($list);
            }
            $this->assign('typed',$typed);
            $this->assign('type',$type);
            return $this->fetch();
        }else{
            echo '参数错误';
        }
    }

    //存颜色
    public function lottery_color(){
        $user_id=session('user.user_id');
//        $user_id=1;//在前端登录做好之前用
        if(!isset($user_id) || $user_id<=0){
            $this->ajaxReturn(['status'=>-1,'msg'=>'请先登录']);
        }
        $type=input('type');
        $num=input('num');
        $group=input('group');
        $color=input('color');

//        echo $type."~~~".$num."~~~".$group."~~~".$color;die;
        if(in_array($type,array(1,2,3,4)) && in_array($group,array(1,2,3,4,5,6)) && in_array($num,array(0,1,2,3,4,5,6,7,8,9,10)) && mb_strlen($color)==6){
            //先看看有没有记录
            $is_have=Db::name('lottery_color')->where(['type'=>$type,'user_id'=>$user_id,'group'=>$group,'number'=>$num])->count();
            if($is_have){
                $res=Db::name('lottery_color')->where(['type'=>$type,'user_id'=>$user_id,'group'=>$group,'number'=>$num])->update(['color'=>$color,'update_time'=>time()]);
            }else{
                $res=Db::name('lottery_color')->insert(['user_id'=>$user_id,'type'=>$type,'group'=>$group,'number'=>$num,'color'=>$color,'create_time'=>time(),'update_time'=>time()]);
            }
            $this->ajaxReturn(['status'=>$res,'mas'=>'变更成功']);
        }
    }
    //查颜色
    public function get_lottery_color($user_id=1,$type,$num,$is_date=0){
        if($is_date){
            $start_color=array('FFFFFF','FFFFFF','FFFFFF','FFFFFF','FFFFFF','FFFFFF');
        }else{
            $start_color=array('060835','060835','060835','060835','060835','060835');
        }
        if(in_array($type,array(1,2,3,4)) && in_array($num,array(0,1,2,3,4,5,6,7,8,9,10)) && $user_id>0){
            $lottery_color=Db::name('lottery_color')->where(['type'=>$type,'user_id'=>$user_id,'number'=>$num])->select();
            if(isset($lottery_color)&&!empty($lottery_color)){
                foreach($lottery_color as $key=>$value){
                    $start_color[$value['group']-1]=$value['color'];
                }
            }
        }
        return $start_color;
    }
    //获取最新一条记录
    public function new_lottery(){
        $type=input('type');
        $lottery_date=input('lottery_date');
        $user_id=session('user.user_id');
//        $user_id=1;//用到登录做好了
        if($user_id>0 && in_array($type,array(1,2,3,4)) && $lottery_date>0){
            $new_lottery=Db::name('interface_recorder')->where(['type'=>$type])->where('lottery_date','>',$lottery_date)->find();
            //初始化六十个白色球
//            var_dump($new_lottery);die;
            if(isset($new_lottery) && !empty($new_lottery)){
                $data['lottery_time']=date('Y',$new_lottery['lottery_time'])."年".date('m',$new_lottery['lottery_time'])."月".date('d',$new_lottery['lottery_time']).'日'.' '.date('H:i:s',$new_lottery['lottery_time']);
                $data['lottery_number']=explode(',',$new_lottery['lottery_number']);
                $data['lottery_date']=$new_lottery['lottery_date'];
                $lottery_number=explode(',',$new_lottery['lottery_number']);
                foreach ($lottery_number as $k=>$v){
                    $data['lottery_color'][$k."-".$v]=array('060835','060835','060835','060835','060835','060835');
                }
//                var_dump($data['lottery_color']);die;
                //看看有没有配过色
                $lottery_color=Db::name('lottery_color')->where(['user_id'=>$user_id,'type'=>$type])->order('group asc')->select();
                if(isset($lottery_color) && !empty($lottery_color)){
//                    var_dump($lottery_color);die;
                    foreach ($lottery_color as $key=>$value){
                        foreach ($lottery_number as $ke=>$va){
                            $data['lottery_color'][$ke.'-'.$value['number']][$value['group']-1]=$value['color'];
                        }
                    }
                }
//                var_dump($data);
                $this->ajaxReturn($data);
            }
        }
    }
}

































